version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Preparing the build..."
      - npm run build
      - echo "Logging in to Docker registry..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-ci-cd-react-app:latest" .
      - echo "Pushing Docker image to the registry..."
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-ci-cd-react-app:latest"
  post_build:
    commands:
      - echo "Build and push completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: .
